apiVersion: v1
kind: ConfigMap
metadata:
  name: starborn-events-config
  labels:
    db: starborn-events
data:
  init.sql: |
    CREATE DATABASE starborn_events;

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: starborn-events
  labels:
    db: starborn-events
spec:
  selector:
    matchLabels:
      db: starborn-events
  template:
    metadata:
      labels:
        db: starborn-events
    spec:
      containers:
        - name: starborn-events
          image: postgres:17-alpine
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: starborn-events-config-volume
      volumes:
        - name: starborn-events-config-volume
          configMap:
            name: starborn-events-config

---

apiVersion: v1
kind: Service
metadata:
  name: starborn-events
  labels:
    db: starborn-events
spec:
  type: ClusterIP
  selector:
    db: starborn-events
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
